CREATE SCHEMA IF NOT EXISTS hakaman;
DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id LONG NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    score LONG DEFAULT 0,
    stageId LONG NOT NULL DEFAULT 0,
    UNIQUE (username)
);

DROP TABLE IF EXISTS question;
CREATE TABLE question (
  id LONG NOT NULL AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR NOT NULL,
  UNIQUE (content)
);

DROP TABLE IF EXISTS answer;
CREATE TABLE answer (
  id LONG NOT NULL AUTO_INCREMENT PRIMARY KEY,
  questionId LONG NOT NULL,
  charkey VARCHAR NOT NULL,
  content VARCHAR NOT NULL,
  correct BOOLEAN DEFAULT false,
  FOREIGN KEY (questionId) REFERENCES question(id),
  UNIQUE (charkey, content)
);
